name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,build-QT_2DGraphicsModeler-Desktop_Qt_6_4_0_MinGW_64_bit-Debug,QT_2DGraphicsModeler/.qtc_clangd,QT_2DGraphicsModeler/debug,QT_2DGraphicsModeler/release,QT_2DGraphicsModeler/Makefile,QT_2DGraphicsModeler/Makefile.Debug,QT_2DGraphicsModeler/Makefile.Release,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro.user,diagram,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro.user.1be1a6f,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro.user.1e467d1,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro.user.1e467d1,QT_2DGraphicsModeler/QT_2DGraphicsModeler.pro.user.8db1f1a,QT_2DGraphicsModeler/.qmake.stash,   "
